### ISSUE TITLE
Crashing when I sleep.

### ISSUE THREAD

**Issue by Shipht8** [SkyrimLL/SDPlus#1052]
When I sleep in Skyrim, the game would load like entering a new area before crashing. I have tested SD disabled and the game dosent crash. I am trying to figure out how to fix this. XPMS is installed and working, so that known issue is crossed out.  

I run SE version of Skyrim and got SE convert of SD+  Any help would be appreciated! Thanks!  

Screen shots are the current mods I am using if anyone is curious (Prob not gonna get anymore soon.)

![currentmods1](https://user-images.githubusercontent.com/81355278/112451159-2b9ccc00-8d23-11eb-9267-e131cf487c0c.PNG)
![Currentmods2](https://user-images.githubusercontent.com/81355278/112451171-2dff2600-8d23-11eb-8730-b0494ddf7fff.PNG)
![currentmods3](https://user-images.githubusercontent.com/81355278/112451177-3192ad00-8d23-11eb-88e3-60ba9f2c48ed.PNG)
![currentmods4](https://user-images.githubusercontent.com/81355278/112451179-335c7080-8d23-11eb-9303-db3fb1e4458b.PNG)
![currentmods5](https://user-images.githubusercontent.com/81355278/112451183-33f50700-8d23-11eb-9b44-c8e976ae54f0.PNG)
![currentmods6](https://user-images.githubusercontent.com/81355278/112451187-35263400-8d23-11eb-919d-d703c95e8b14.PNG)
![currentmods7](https://user-images.githubusercontent.com/81355278/112451212-3eaf9c00-8d23-11eb-93db-5b54ea6aeaec.PNG)
![currentmods8](https://user-images.githubusercontent.com/81355278/112451226-42432300-8d23-11eb-9253-aa08af197ef6.PNG)

**Comment by SkyrimLL** [comment]
Please ask this kind of question in my SE discussion thread on Lovers Lab. Others who are using SE can see it there and maybe answer it. I am not using SE myself and I can't help much on that matter at the moment.
