### ISSUE TITLE
Furniture props from ZAP missing in some punishment animations

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#23]
Seems to be linked to a timing issue with the scene - not enough time given to show the prop.

When furniture doesn't appear at first, it seems to appear eventually if sexlab tries to start a scene and ends up being cancelled by current scene.

Could be just an issue with my game. Let me know if furniture is missing in yours as well.

**Comment by SkyrimLL** [comment]
I need a better understanding of how to make the punishment scenes bullet proof regarding the use of props in punishment idles.

Running idles manually in the console works, but once they are called inside a scene, props are missing most of the time.

**Comment by ContentConsumer** [comment]
Consider not using props at all?
What I mean is, you could just force the target onto the ground (bindings and use the laying-on-ground-bound-up idle).

Alternately, you could just have master say "stand still while I punish you" and allow the player full control to either stand there and take it or run away - straying outside of a certain radius (like 2x melee combat distance) from your master will trigger a more aggressive punishment, something like the shock collar...?

**Comment by SkyrimLL** [comment]
Intermittent issue, probably due to bad scripting (on my end) and script lag.
Closing for now as I have not see that happening much in recent versions.
