### ISSUE TITLE
Add bounty when escaping

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#286]

**Comment by ContentConsumer** [comment]
Can I make a request?
Only add bounty if you are enslaved to a master who it is appropriate for.
For example, there should be no bounty if you escape from a bandit or falmer or whatever.
It makes no sense for a guard to treat you as a criminal if you've escaped from a bandit. :)

Of course, if the purpose is to add a background penalty for escaping, you could implement an internal, hidden bounty system and add your own thugs or bounty hunters that will try to track you down for escaping - so you aren't a criminal for escaping enslavement from a bandit, but you are still being hunted for doing so.

**Comment by SkyrimLL** [comment]
The idea was that guard would have no way to tell who your master was... just that you are an escaped slave.

So as a runaway slave, you would have the option to pay your 'crime' and walk out of the jail without your collar... or accept to be sold to a new master who is willing to pay your bounty maybe.
