### ISSUE TITLE
Spriggan transformation causes CTD when not using UNPB type bodies

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#289]
Long John - "Also is it possible for this to have please a second small update for the Spriggan transformation parts (early on not knowing about full transformation) causes a CTD when not using UNPB type bodies. Specifically when using a matching pair according to new DDa and DDi specification for non CBBE. This is specifically using DImonized UNP rather than UNPB, is okay rest of the time. Though not when being transformed into a spriggan (crash when transforming under previously mentioned conditions)."

**Comment by MrGrymReaper** [comment]
I am using the following software:

 

"XP32 Maximum Skeleton Extended" version 2.75 with all of its requirements

"HDT Physics Extensions" version 14.28

"HDT HighHeels System" version 0.5

"DIMONIZED UNP female body" version 1.5 (an update released for version 1.2)

"SKSE" version 1.7.2 (new stable release)

"DDa" version 2.9.0

"DDi" version 2.9.0

"Death Alternative" version 6.1.8

"RaceMenu" version 3.2

"Skyrim" version 1.9.32 - From steam with all DLCs.

"ZAZ Animation Pack" version 6.04

"Unofficial Skyrim Patch" version 2.1.1

"Unofficial High Resolution Patch" version 1.1.9a

"Unofficial Hearthfire Patch" version 2.1.1

"Unofficial Dragonborn Patch" version 2.1.1

"Unofficial Dawnguard Patch" version 2.1.1

 

As well as all of the other requirements to use the modification.

 

So yes I'm using an advanced skeleton as XP32 Maximum Skeleton Extended is based on XPMS and has just been extended.

**Comment by bicobus** [comment]
Spriggan transformation work fine with CBBE now, or is there another kind of transformation?
