### ISSUE TITLE
Dushnik Yal blackmith bug

### ISSUE THREAD

**Issue by Gh0sTG0** [SkyrimLL/SDPlus#298]
Have a bug in blacksmith quest in Dushnik Yal. There is no dialogue at the blackmith

**Comment by SkyrimLL** [comment]
There is no dialogue for orc blacksmith except for the one in Markarth. 

Sending you to the orc camp is just an excuse to do the quest that gives you 'blood kin' status.

**Comment by Gh0sTG0** [comment]
I'm now a blook kin, what next? Did the quest without cheats, become blood kin, your quest didn't changed
