### ISSUE TITLE
Add option for female on top when male player is enslaved by mistress

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#303]

**Comment by ContentConsumer** [comment]
This is for player-on-bottom
sexActors[0] = Player reference
sexActors[1] = NPC reference

This is for player-on-top
sexActors[0] = NPC reference
sexActors[1] = Player reference

And just add a couple of if/elif checks for gender - if player is male && npc is female, put player on bottom. That kind of thing.

**Comment by SkyrimLL** [comment]
Set to happen 70% of the time.
