### ISSUE TITLE
Remove abusive message about weapon unequipped when enslaved

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#310]
Issue with invisible weapons mods like SPERG.

**Comment by ContentConsumer** [comment]
I suppose you could filter out weapon types by keyword... that is, anything labeled as a sword is a weapon, but stuff labeled "fists" are not...???

**Comment by SkyrimLL** [comment]
I am already filtering by item type. Invisible fists are also labeled as weapons.

I will disable this message for now and revisit this later.
