### ISSUE TITLE
Add transfer of ownership actions

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#32]
- If master is nearby and happy, start a brawl with new master
  :: Implemented but left as 'cosmetic' option - master starts brawl and stops immediately due to 'stop combat' from enslavement sequence
  :: Removing 'stop combat' results in issues when new master is killed before enslavement sequence is complete 
  :: Try making new master essential during enslavement sequence?
- If master is nearby and unhappy, exchange dialogue with new master (good riddance)
- If master is away, increase old master anger, decrease relationship level

**Comment by bicobus** [comment]
I believe these mechanics are implemented and functioning.
