### ISSUE TITLE
Add mod event to add/remove punishment

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#364]
SendModevent("PCSubPunishmentAdd","gag")

**Comment by SkyrimLL** [comment]
Is that really necessary? There is already a EquipDevice mod event.

akSpeaker.SendModEvent("SDEquipDevice", "Gag", 1)

**Comment by ContentConsumer** [comment]
Why rewrite code that already exists? SDEquipDevice seems like it's a bit better anyway (I haven't looked at the code, but I'm guessing that the '1' is a bool check for equip / unequip).

**Comment by SkyrimLL** [comment]
@ContentConsumer That '1' is an optional outfit ID.
There is a similar 'removeDevice' mod event.

I really need to spend time writing a better API documentation.
