### ISSUE TITLE
Allow changing slave rags configuration during enslavement

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#376]
Currently, the choice of default or custom slave rags outfit has to be done BEFORE being enslaved.

**Comment by ContentConsumer** [comment]
Well, yeah. Your master determines what you wear, right? As a slave, I don't have that option, I think...
I would put it behind a wall - you can only choose what to wear when your relationship with your master has become solidly positive.
Or maybe it depends on your master's personality/objectives.

**Comment by ContentConsumer** [comment]
Uh... never mind, I misunderstood what you were talking about. My bad. :)

**Comment by SkyrimLL** [comment]
Yeah... when I fixed the broken custom slave rags from the old SD, I realized the configuration is used to fill a quest alias, which means it is only valid at the start of the enslavement quest.

I need to change it to force an update of the alias if the option is changed while an enslavement is already in place.
