### ISSUE TITLE
spriggan item not removed even when talking to Danica Pure-Spring

### ISSUE THREAD

**Issue by Draic** [SkyrimLL/SDPlus#386]
even after finishing the first quest and waiting the needed amout of time the roots were still on my hands.

Talking with Pure-Spring and asking for help triggered the dialogue that now all items are removed but that was not the case. Still wearing the roots and no way to remove them

**Comment by SkyrimLL** [comment]
It is possible the new Device removal system broken Spriggan items.
I will check that out,
