### ISSUE TITLE
Game crashes when I sleep in front of Sanguine's shrine thing

### ISSUE THREAD

**Issue by cardiffcal** [SkyrimLL/SDPlus#509]
Every time I sleep in front of the shine my screen goes into the loading screen and then shuts down like a forced quit the program. 
My load order is (from first to last) 
skyrim, update, dawnguard, hearthfire, schlongs of skyrim core, sexlab, sexlabaroused, zazanimation, deviousdevices (assets), daymoyl, deviousdevices (intergration), sanguinesdebuchery, skyUI, Schlongsofskyrim, sosshop, dD realisticragdollforce, racemenu, racemenuplugin, sosvectorplexus addon, FNIS, sexlab romance, bathing in skyrim, sosracemenu, deviousdeviants, sexlabdiologues 

ANY help would be MASSIVELY appreciated.

**Comment by SkyrimLL** [comment]
The first thing to check is if you have a skeleton like XPMS installed. This is a usual source of crash in Dreamworld.

Another possibility has to do with randomization of Sanguine's shape nodes and how they are applied.  I am switching to NiOverride, which should reduce the possibility of crash. That will be part of the next update.

**Comment by SkyrimLL** [comment]
No feedback since July - closing for now.
