### ISSUE TITLE
SD+ configuration addon

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#523]
- Add option for slavery level based outfit (Add min slavery level + max slavery level for each outfit)
- Options to set color of outfits
- Options to set outfits in game (MCM)

**Comment by ContentConsumer** [comment]
I had the idea to add color settings to the SD Addons. I don't have any code to put to it unless you have storageutil or modevents set up yet, but it's easy enough to add.
Not sure how to do slavery level, but IIRC it's also a storageutil variable, right? I should be able to check that and then set another one...?

**Comment by SkyrimLL** [comment]
The colors are simply more tags for the generic device... just add them after the other tags, like 'leather,red' instead of just 'leather'.
Issue is that the list of colors is not predictable. It can be red, white, black depending on mods like Captured Dreams. You would have to check for the availability of devices for these tags first using the DDi API. 

For the slavery level, I have both a global variable and a storageutil one. I will have to detect if the storageutil one changed in order to update the global variable.
