### ISSUE TITLE
Stuck after bleedout

### ISSUE THREAD

**Issue by Syarx** [SkyrimLL/SDPlus#596]
New save, I got to bleak falls and die by the bandits and after the bleedout i am left lying there and nothing  happens. I have unchecked all non SD options in DA for blackout radiant and death. Also the enslavement chance is at 100%. No mods that alter factions also. Also |\ button doesn't do anything. Help

**Comment by SkyrimLL** [comment]
This is probably related to initialization issues that recently plagued the mod.
Try upgrading to version 3.5.3 (released today).
You may have to start a new game to clear these issues.
