### ISSUE TITLE
Add topic option for voluntary punishments

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#644]
"Master... I have been very bad,"

Same as sex, option should increase negative allowance until it reaches 0.

**Comment by bicobus** [comment]
"Punishments" could also come with what the owner wants. I don't know how you weight the owner's needs, or if it is totally random, but the outcome of asking the "what do you want?" question should probably be linked with the actual needs of the owner, listed in the daily summary.

**Comment by SkyrimLL** [comment]
Fixed in #775
