### ISSUE TITLE
Add devices from DD Extension as punishment

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#645]
Tags to use: https://github.com/DeviousDevices/Docs/wiki/Generic-item-tags
And: https://github.com/DeviousDevices/DDx/blob/master/00%20Core/Scripts/Source/zadxLibs.psc#L861

- boots
- gloves
- chain harness
- chain mittens
- different types of gags for different offenses

**Comment by bicobus** [comment]
Devices can also be worn for their ornamental values, given to the player when asking "what do you want?". Could depend on the slavery level the player is currently in, a base slave will just get irons where a trained slave will get beautiful leather.

**Comment by SkyrimLL** [comment]
That would require too much rewrite for now. I set up styles of slavery gear by race of the master, not by slavery level + race. That would just introduce too many variations.

That said it is a good idea to add that to 'what do you want' and add a chance the master will add some items to the player just because they feel like it (piercing for example).

I am also looking into adding items as punishment or reward for certain tasks.

**Comment by SkyrimLL** [comment]
The new task system is adding more devices as punishment, reward or just for training:

* training plugs, gag and boots
* nipple piercings as reward
* punishment devices will be added later.
