### ISSUE TITLE
Find solution when master inventory is full

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#650]
- [ ] Regularly clean up food / junk items from inventory
- [ ] Ask player to take some items, sell them and return with profit?
- [ ] Use items from inventory when player asks master for food/drinks

**Comment by ContentConsumer** [comment]
Something else to consider too: there are eating and drinking animations. A particularly cruel master might, when the (untrusted) slave asks for food and drink, chug a bottle of ale or cram a loaf of bread then laugh. :)

**Comment by SkyrimLL** [comment]
Good idea with the animation. I could make that a random event.

My current thinking to solve this problem is to treat the master as a walking inventory with restrictions.

When the player asks for food, drinks or potions, the master would open a gift inventory filtered by item type. That way the master would only provide what you brought to him in the first place.

That would be both an incentive for the player to bring stuff to the master and a way to regularly remove things from the master's inventory. Not counting it would be a more realistic system anyway.

**Comment by bicobus** [comment]
Could trim the inventory on a daily basis too. For example, remove a set amount of gold from the owner and replace with food/drinks. You can weight the ratio given the location: food would be more expensive in the wilderness than in or near a city.

**Comment by ContentConsumer** [comment]
If you do that, I'd suggest removing gold and replacing with goods only when in an urban environment - I mean a city, town, or dungeon populated with people of the master's own faction. It doesn't make much sense for the master to be using the gold you give him to buy potions from, for example, trees and rocks. ;)

**Comment by SkyrimLL** [comment]
I won't go into analyzing the master's location. Places are not consistently tagged anyway and I don't want to have scripts with a zillion of properties to cover most types of places.

I will try to keep it simple for now - just open the inventory and pick from what the master has at the moment.

That will also prevent a cheat I have been using a lot - a cheap way to find food, drinks and potions by just talking to a total stranger and asking Please.
