### ISSUE TITLE
Add chance master will equip items given by player

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#656]

**Comment by ContentConsumer** [comment]
Might be a bit tough, though - NPCs are notorious for failing to equip or keep equipped any gear you give them. Usually when you leave them alone for a while, but sometimes (rarely) on a simple exit and reload, they'll just re-equip their default outfit.

**Comment by SkyrimLL** [comment]
I'm OK with these issues. The point is to equip the items (even temporarily) or consume what can be consumed to reduce items in inventory. The goal is to show immediate effect of the master's actions.
