### ISSUE TITLE
Dialogues for creature masters is often frozen (displayed but not clickable)

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#657]
- Looks similar to #169 
- Usually cleared after reload or wait in game for a few hours
- Could be related to unfinished scene, preventing dialogues until it times out

**Comment by bicobus** [comment]
Also cleared by disabling then enabling the actor.

**Comment by SkyrimLL** [comment]
I created a test spell to debug the state of the NPC you are interacting with. The spell will be in a hidden book you can get from the console (in the next version of Dialogues - v2.9.0).

The spell checks for sexlab animation factions, combat state, and current package. 

So far, I have not been able to pinpoint what is causing the issue.

All I know is that:
- the issue doesn't have a clear trigger. It is seemingly random (so if it has a trigger, it is silent)
- the issue is not related to an AI package (I check the package the NPC is in when the dialogues are stuck and it is the same packages as when dialogues are not stuck).
- the issue is cleared after a certain amount of time, after reloading the game or after resetting the NPC
- no error message in the logs pointing to an issue so far

**Comment by bicobus** [comment]
> the issue doesn't have a clear trigger. It is seemingly random (so if it has a trigger, it is silent) but it happens relatively quickly after being enslaved (or after a game reload while being enslaved)

In my experience, the issue happens after interacting with the owner. You talk to the beast, and after a while the bug kicks in and the actor becomes unresponsive - as in the owner is waiting for the completion of a routine. If it is so, it wouldn't return any error or even log anything since the actor is just waiting.

Resetting or waiting would make the routine "timeout". Thus it may just be an infinite loop of some kind.

If you can, could you add log points in your dialogue calls, at each levels. That'll be spammy and dirty, but you'll see at which point the code stops from being executed. The best way to go about it would have a "called function X" and in said function "Executed function X". Would be best to put all that log in a dedicated file though, like inflation and Sexlab are doing.

**Comment by SkyrimLL** [comment]
Based on jbezorg's comment, next step is to test conditions for snp scripts and scenes.

**Comment by SkyrimLL** [comment]
What is infuriating in this dialogue issue is that it only happens with creature owners. I haven't experienced it once with humanoid owners.
 
If is not an issue with DefaultAllowPCDialogueScript as that script only uses AllowPCDialogue() . When I cast my debug spell on stuck NPCs, I use that as well and their dialogue remains stuck.
 
Besides, the dialogues ARE displayed. They are just not clickable (or selectable with the Enter key).
 
I did find some issues with the different states of the master monitoring/searching for the slave, so this debugging is not in vain. But the main issue is still eluding me.
 
If you have this issue in your game:
 
- are you using the EZ2C dialogues mod?
- are you sing EFF? AFT? or another follower mod, and which one?

**Comment by SkyrimLL** [comment]
I can say (almost) for certain that the issue is linked to a 'NPC follow player' behavior when the player gets far enough from the NPC owner.

One way to reproduce the issue:

- stay close to the owner and make sure dialogues do work
- start walking away backwards slowly
- stop as soon as the owner starts moving towards you
- the owner should now have disabled dialogues.

The follow behavior happens before a change of state in the master routine (I added debug statements on state changes), so it is triggered outside of the master behavior script.

**Comment by SkyrimLL** [comment]
Try these commands ingame:

- getcurrentpackage
- sv

http://elderscrolls.wikia.com/wiki/Console_Commands_(Skyrim)

**Comment by SkyrimLL** [comment]
Turns out the issue happens also when player is not enslaved... so it is unlikely to be caused by SD+ follow packages.

Back to square one. Looking at Dialogues instead.

**Comment by SkyrimLL** [comment]
Interestingly, I was not able to reproduce the issue with a named pet like Meeko (which happens to be also a follower).

I will see if making an animal master a follower helps with the issue.

**Comment by SkyrimLL** [comment]
As a final clue for today, I found I could not reproduce the bug with a dog (meeko) and wolves as masters.
With falmers and trolls, the bug happens within a few minutes.
I suspect chaurus also trigger the bug but I haven't tested them lately.

**Comment by SkyrimLL** [comment]
Next stop - check for differences with skeleton, distance to player, built-in behaviors and animations based on race.

**Comment by SkyrimLL** [comment]
Note: Look at Campfire follower quest for potential interference.

**Comment by SkyrimLL** [comment]
Closing issue for now.
I added a replacement dialogue system for creatures using a popup menu + menu option to toggle between the two menu systems.
