### ISSUE TITLE
Randomly crawling

### ISSUE THREAD

**Issue by Jeremiahp15** [SkyrimLL/SDPlus#681]
Hello everyone. I suspect the mod adding crawling animation is SD+ and so I have an issue, my character starts to randomly crawl for no reason, i can fix it by resetting the animations through PCEA2 but after a while my character starts to crawl again. It started when I was talking to Ulfric for the peace treaty, my character while in dialogue started kneeing, and then got on all 4's, after that she keeps randomly getting on all 4's. That's about 7 hrs into the game and I keep different saves for doing the adult quest mods.

**Comment by SkyrimLL** [comment]
The only thing I can think of is to check the key mappings to stand up, kneel or crawl. 
By default, they are mapped to the arrow keys (up and down). 
Try mapping the actions to another set of keys from the SD+ menu and see if that helps.
I am closing this report and will reply as well on the forum in LL.
