### ISSUE TITLE
Kneeling and Crawling dosent work anymore

### ISSUE THREAD

**Issue by saw7036** [SkyrimLL/SDPlus#683]
it randomly stopped working for me, but the collars that make you kneel still works but the button's to do so does not

**Comment by bicobus** [comment]
You need to provide more information for a proper help of troubleshooting. For instance, a papyrus log to see if the animations are properly initialized.

**Comment by SkyrimLL** [comment]
Closing this issue as the kneeling/crawling system has been redefined in 3.6.1
