### ISSUE TITLE
'Blacksmith Craft' quest line is missing objective markers.

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SDPlus#691]
At last the first 5+ starting objectives miss a marker pointing where to go or update when a requirement is met (obtaining a requested item.)

I haven't gone farther in so I'm assuming the entire quest line is that way.

**Comment by SkyrimLL** [comment]
This is partly by design (I miss the markerless quests from Morrowind) and partly because I always had issues getting quest markers right.
