### ISSUE TITLE
Issue with armbinder effect from SD+ and DDi 4.0

### ISSUE THREAD

**Issue by SkyrimLL** [SkyrimLL/SDPlus#714]
`[12/24/2017 - 12:05:42AM] warning: Property idles on script zadArmbinderEffect attached to Active effect 7 on  (00000014) cannot be initialized because the script no longer contains that property`

In addition to error log:

- [x] - inventory is still accessible (normal in DD4)
- [x] - solo animations ignore armbinders (turn on Bound animation filter)
- [ ] - player should be able to jump
- [x] - armbinders not removed when punishment ends (issues with new keywords, should be fixed now)
- [x] - Yokes are not detected and added properly anymore (issues with new keywords, should be fixed now)

Check if property values are missing on all devices + check for missing new keywords.

**Comment by LazyBoot** [comment]
The warning is because the DD team forgot to remove the property in the esm after removing it from the script.

Also, having inventory access is normal and intended.
