### ISSUE TITLE
SD+ stance changes remove currently selected FNIS Sexy Move animations

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SDPlus#763]
Switching to an SD+ stance then back to standing causes the currently selected FNIS Sexy Move animation to no longer apply. This happens even if your SD+ stance doesn't change (pressing the up arrow while already standing or attempting to change stances when not enslaved.)
If the 360 style walk/run animations pack from FNIS Sexy Move is installed it will also be unapplied.

In order to reapply the animations from FNIS Sexy Move you have to go back into the MCM menu and toggle animations every time it happens.

**Comment by SkyrimLL** [comment]
I think this is related to the bug report about PCEA idles being wiped by SD+ as well. 

This was originally happening when I was trying to do my own idle management in SD+ by duplicating code from DD but that also introduced a dependency on using FNIS sexy moves code to compile SD+ scripts. 

I replaced that by using direct calls to DDi functions instead and let DD handle all animations. That was working for DDi 3 but that seems to have changed in DDi 4.

I am putting this on on hold for a while as I have other priorities at the moment (SD+ cages and task system, main quest in SD+, main quest in Parasites). I will revisit this in a few months unless someone can take the time to troubleshoot and provide me with a fix of course :)

**Comment by ThisIsPatrick** [comment]
I've tracked down the issue and have opened a pull request at the DDi repo with a fix.
https://github.com/DeviousDevices/DDi/pull/181

**Comment by SkyrimLL** [comment]
Should I understand from the comments on that thread that the issue has been resolved and will be available in future versions?

**Comment by ThisIsPatrick** [comment]
That is correct.
