### ISSUE TITLE
SD+ Quest Doesn't Start

### ISSUE THREAD

**Issue by abuguia** [SkyrimLL/SDPlus#821]
Hi!

The dreamworld and MOD in MCM looks good (installed), but the slavery quest after defeated doesn't start, even with surrender/submit key or on Blackout Event (with all probabilities configured to 100%). I'm using version 3.6.

**Comment by SkyrimLL** [comment]
Please post this kind of issue in the support thread [](https://www.loverslab.com/topic/24042-sd-sanguine-debauchery-enhanced-2018-02-10/) along with an error log generated during an enslavement attempt.
