### ISSUE TITLE
Player defiance gets stuck at "mostly Defiant"

### ISSUE THREAD

**Issue by dances-with-peons** [SkyrimLL/SDPlus#862]
Characters that have been around a while, and have a history of both Submitting and Resisting, end up as "mostly Defiant (0)". Further Submit or Resist responses no longer change the value.

It looks like this is because of the way defiance is calculated. In `SDPlus/SanguineDebauchery/Data/scripts/source/_sdqs_fcts_slavery.psc`, function `UpdateStatusDaily` (around line 745), `iDominance` is simply a difference between iDom and iSub (line 773), *after* both have been clamped to -10...+10. Submitting increases iSub, and resisting increases iDom, but they don't usually decrease. (I only see one place where the iDom value decreases.) Once you've Submitted and Resisted 10 times each, if i'm reading the code correctly, `iDominance` ends up being 10 - 10 == 0, and doesn't change from then on.

Things should at least work if the subtraction is done on the raw iDom and iSub values, and the result gets clamped instead. But that still leads to awkwardness where someone could Resist dozens of times in a row and still be "mostly Submissive".

**Comment by SkyrimLL** [comment]
Thanks for the report. I think part of the problem is that I meant to update the sub/dom values after clamping them down. I changed that now.
I also added a small forced cooldown of the dom side during enslavement so that if you don't show defiance, it will naturally decrease down to -10.
